### ISSUE TITLE
More descriptive names for output folders; 'domain-extension-date'

### ISSUE THREAD

**Issue by PrijsDF** [MarchalMaxim/webcrawler#11]

**Comment by MarchalMaxim** [comment]
Putting a domain  in a filename is tricky, because you're embedding a URL in a URI.
A possibility: replace the / in the paths with another token, like | or .

**Comment by MarchalMaxim** [comment]
Fixed, do `git checkout descriptive-names-11`  (or checkout commit e81ceb17d5f8e692356013485125891125771880)
