### ISSUE TITLE
Currently elements with hrefs pointing to images are crawled, resulting in screenshots of these images 

### ISSUE THREAD

**Issue by PrijsDF** [MarchalMaxim/webcrawler#3]
Solution might be to ignore elements containing a href to image files (.jpg, .png, etc)

**Comment by MarchalMaxim** [comment]
Steps to reproduce: run a full scan with ROOT_DOMAIN = kuipris.nl.

**Comment by MarchalMaxim** [comment]
Fixed in 6262b9d49ea95d4fae467a7132744e7e6abcb7ae by implementing functionality where the user can configurate the file extensions they want to ignore.
