### ISSUE TITLE
Crawler visits 'hidden' hrefs found in <head> section of the document

### ISSUE THREAD

**Issue by PrijsDF** [MarchalMaxim/webcrawler#4]
This causes it to follow irrelevant pages and files, such as the WordPress admin panel on WP websites

**Comment by MarchalMaxim** [comment]
Steps to reproduce: run a full scan with ROOT_DOMAIN = kuipris.nl.

**Comment by MarchalMaxim** [comment]
Steps to reproduce?

**Comment by MarchalMaxim** [comment]
fixed in latest merge.
